version: '3.9'

services:
  api:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8080:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
      - mongo
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  postgres:
    image: postgres:15
    volumes:
      - postgres_data_employee:/var/lib/postgresql/data
    env_file:
      - ./.env

  mongo:
    image: mongo
    volumes:
      - mongo_data_speakers:/data/db
    env_file:
      - ./.env

volumes:
  postgres_data_employee:
  mongo_data_speakers:
